package restaurant.server.ui.form;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import restaurant.server.admin.Admin;
import restaurant.server.communication.Server;
import restaurant.server.connection.MyDatabaseConnection;
import restaurant.server.session.Session;
import restaurant.server.thread.ActiveClientsThread;
import restaurant.server.thread.ProcessClientRequests;
import restaurant.server.ui.ClientsTableModel.ClientsTableModel;
import restaurant.server.ui.form.about.ServerAboutForm;
import restaurant.server.ui.form.add.AdminAddForm;
import restaurant.server.ui.form.info.ServerInfoDialog;

/**
 *
 * @author Natasa Todorov Markovic
 */
public class MainForm extends javax.swing.JFrame {

    private Server server;
    private ActiveClientsThread activeClients;
    private Admin admin;

    private final ClientsTableModel model;

    /**
     * Creates new form MainForm
     */
    public MainForm(Admin admin) {
        initComponents();
        setLocationRelativeTo(null);
        this.admin = admin;
        model = new ClientsTableModel(new ArrayList<>());
        tblClients.setModel(model);
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnStartServer = new javax.swing.JButton();
        btnStopServer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClients = new javax.swing.JTable();
        lblAdmin = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuServer = new javax.swing.JMenu();
        menuItemInfo = new javax.swing.JMenuItem();
        menuItemRegister = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        menuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnStartServer.setText("Start server");
        btnStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartServerActionPerformed(evt);
            }
        });

        btnStopServer.setText("Stop server");
        btnStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopServerActionPerformed(evt);
            }
        });

        jLabel1.setText("Clients:");

        tblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblClients);

        lblAdmin.setText("jLabel2");

        menuServer.setText("Server");

        menuItemInfo.setText("Info");
        menuItemInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInfoActionPerformed(evt);
            }
        });
        menuServer.add(menuItemInfo);

        menuItemRegister.setText("Register new admin");
        menuItemRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRegisterActionPerformed(evt);
            }
        });
        menuServer.add(menuItemRegister);

        jMenuBar1.add(menuServer);

        menuHelp.setText("Help");

        menuItemAbout.setText("About");
        menuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAboutActionPerformed(evt);
            }
        });
        menuHelp.add(menuItemAbout);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnStartServer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStopServer)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdmin)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStartServer)
                    .addComponent(btnStopServer))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartServerActionPerformed
        if (server == null || !server.isAlive()) {
            server = new Server();
            server.start();
            setTitle("Server is up and running");
            activeClients = new ActiveClientsThread(tblClients, model);
            activeClients.start();
            btnStartServer.setEnabled(false);
            btnStopServer.setEnabled(true);
        }
    }//GEN-LAST:event_btnStartServerActionPerformed

    private void btnStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopServerActionPerformed
        if (server != null && server.isAlive()) {
            server.stopServer();
            setTitle("Server stopped");
            activeClients.interrupt();
            tblClients.setModel(new ClientsTableModel(new ArrayList<>()));
            btnStartServer.setEnabled(true);
            btnStopServer.setEnabled(false);
        }
    }//GEN-LAST:event_btnStopServerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            MyDatabaseConnection.getInstance().closeConnection();
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void menuItemInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInfoActionPerformed
        new ServerInfoDialog(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemInfoActionPerformed

    private void menuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAboutActionPerformed
        new ServerAboutForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemAboutActionPerformed

    private void menuItemRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRegisterActionPerformed
        new AdminAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemRegisterActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartServer;
    private javax.swing.JButton btnStopServer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuItemAbout;
    private javax.swing.JMenuItem menuItemInfo;
    private javax.swing.JMenuItem menuItemRegister;
    private javax.swing.JMenu menuServer;
    private javax.swing.JTable tblClients;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        List<ProcessClientRequests> clients = Session.getInstance().getClients();
        model.updateTable(clients);
        lblAdmin.setText("Ulogovani ste kao: "+admin.getFirstname()+" "+admin.getLastname());
    }

    public JTable getTblClients() {
        return tblClients;
    }
}
