package restaurant.common.transfer;

/**
 *
 * @author Natasa Todorov Markovic
 */
public enum Operation {
    
    LOGIN,END,
    
    USER_ADD,USER_GET_ALL,USER_FIND_BY_ID,USER_DELETE,USER_UPDATE,
    
    ROLE_GET_ALL,
    
    MENU_ITEM_ADD,MENU_ITEM_GET_ALL,MENU_ITEM_GET_ALL_BY_CATEGORY,MENU_ITEM_GET_ALL_BY_TYPE,MENU_ITEM_UPDATE,MENU_ITEM_DELETE,MENU_ITEM_FIND_BY_ID,
    
    MENU_CATEGORY_GET_ALL,MENU_CATEGORY_ADD,
    
    
    MENU_ADD,MENU_FIND_BY_ID,MENU_GET_ALL,MENU_GET_MENU_ITEMS_BY_CATEGORY,MENU_UPDATE,MENU_DELETE,MENU_ADD_MENU_ITEM,MENU_DELETE_MENU_ITEM,MENU_GET_ALL_BY_STATUS,
    
    TABLE_ADD, TABLE_GET_ALL, TABLE_DELETE, TABLE_UPDATE, TABLE_IS_AVAILABLE,TABLE_SET_IS_AVAILABLE,
    
    EMPLOYEE_GET_ALL, EMPLOYE_FIND_BY_ID, EMPLOYEE_ADD,EMPLOYEE_UPDATE,EMPLOYEE_DELETE,
    
    
    CITY_GET_ALL, CITY_ADD,
    
    ORDER_ADD,ORDER_FIND_BY_CONDITION,ORDER_GET_ALL,ORDER_FIND_BY_ID,ORDER_UPDATE,
    
    ORDERITEM_FIND_BY_QUERY,ORDERITEM_FIND_BY_ID,ORDERITEM_UPDATE,
    
    RECEIPT_ADD, RECEIPT_GET_ALL,RECEIPT_FIND_BY_ID,RECEIPT_FIND_BY_QUERY,RECEIPT_FIND_UNPAIED_BY_EMPLOYEE,
    
    PAYMENT_ADD,PAYMENT_GET_ALL,PAYMENT_FIND_BY_RECEIPT
    
    
    
}
