package restaurant.client.ui.form.mainForm;

import java.util.logging.Level;
import java.util.logging.Logger;
import restaurant.client.communication.Communication;
import restaurant.client.session.ApplicationSession;
import restaurant.client.ui.form.Menu.MenuAddForm;
import restaurant.client.ui.form.Menu.MenuSearchForm;
import restaurant.client.ui.form.Menu.MenuUpdateDeleteForm;
import restaurant.client.ui.form.employee.EmployeeAccountUpdateDeleteForm;
import restaurant.client.ui.form.employee.EmployeeAddForm;
import restaurant.client.ui.form.employee.EmployeeCreateAccountForm;
import restaurant.client.ui.form.employee.EmployeeSearchForm;
import restaurant.client.ui.form.login.controller.LoginFormController;
import restaurant.client.ui.form.loginForm.LogInForm;
import restaurant.client.ui.form.menuItem.MenuItemAddForm;
import restaurant.client.ui.form.menuItem.MenuItemSearchForm;
import restaurant.client.ui.form.order.OrderBartenderForm;
import restaurant.client.ui.form.order.OrderChefsForm;
import restaurant.client.ui.form.order.OrderCreateForm;
import restaurant.client.ui.form.order.OrderPreparePaymentForm;
import restaurant.client.ui.form.order.OrderSearchForm;
import restaurant.client.ui.form.receipt.ReceiptSearchForm;
import restaurant.client.ui.form.table.TableSearchForm;
import restaurant.common.domain.User;
import restaurant.common.transfer.Operation;
import restaurant.common.transfer.Request;
import restaurantapp.ui.form.menuCategory.MenuCategoryAddForm;

/**
 *
 * @author Natasa Todorov Markovic
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
       // setMaximumSize(new Dimension(994, 639));
        setResizable(false);
        
        prepareForm();
        
        pack();
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCreateOrder = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnPayment = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnOrderView = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMeals = new javax.swing.JMenu();
        menuItemMenuItemGetAllMeals = new javax.swing.JMenuItem();
        menuItemAddMenuItem = new javax.swing.JMenuItem();
        menuItemAddCategory = new javax.swing.JMenuItem();
        menuMenu = new javax.swing.JMenu();
        menuItemMenuGetAll = new javax.swing.JMenuItem();
        menuItemCreateNewMenu = new javax.swing.JMenuItem();
        menuItemUpdateMenu = new javax.swing.JMenuItem();
        menuTables = new javax.swing.JMenu();
        menuItemTablesSerach = new javax.swing.JMenuItem();
        menuEmployee = new javax.swing.JMenu();
        menuItemEmployeeSearch = new javax.swing.JMenuItem();
        menuItemCreateAccount = new javax.swing.JMenuItem();
        menuItemAddEmployee = new javax.swing.JMenuItem();
        menuItemAccountForm = new javax.swing.JMenuItem();
        menuOrder = new javax.swing.JMenu();
        menuItemGetAllOrder = new javax.swing.JMenuItem();
        menuItemCreateOrder = new javax.swing.JMenuItem();
        menuItemPayment = new javax.swing.JMenuItem();
        menuItemChefsOrder = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuReceipt = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogout.setText("Odjavi se");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jelovnik", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnMenu.setBackground(new java.awt.Color(242, 242, 242));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/client/ui/form/mainForm/icons/Restaurant menu free icon 3.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnMenu)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kreiraj porudzbinu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnCreateOrder.setBackground(new java.awt.Color(242, 242, 242));
        btnCreateOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/client/ui/form/mainForm/icons/OrderIcon.png"))); // NOI18N
        btnCreateOrder.setBorder(null);
        btnCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btnCreateOrder)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnCreateOrder)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Naplati porudzbinu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnPayment.setBackground(new java.awt.Color(242, 242, 242));
        btnPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/client/ui/form/mainForm/icons/Long Wallet free icon 1 (1).png"))); // NOI18N
        btnPayment.setBorder(null);
        btnPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnPayment)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnPayment)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pregled porudzbina - Kuhinja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btnOrderView.setBackground(new java.awt.Color(242, 242, 242));
        btnOrderView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/client/ui/form/mainForm/icons/Chef Hat free icon 2 (1).png"))); // NOI18N
        btnOrderView.setBorder(null);
        btnOrderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnOrderView)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnOrderView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pregled porudzbina - Bar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/client/ui/form/mainForm/icons/Tea cup free icon 2.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pregled stolova", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurant/client/ui/form/mainForm/icons/icons8-restaurant-table-100.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray, 8));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(62, 62, 62))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuMeals.setText("Jelo");

        menuItemMenuItemGetAllMeals.setText("Prikaz svih jela");
        menuItemMenuItemGetAllMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMenuItemGetAllMealsActionPerformed(evt);
            }
        });
        menuMeals.add(menuItemMenuItemGetAllMeals);

        menuItemAddMenuItem.setText("Dodaj novo jelo ");
        menuItemAddMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddMenuItemActionPerformed(evt);
            }
        });
        menuMeals.add(menuItemAddMenuItem);

        menuItemAddCategory.setText("Dodaj novu kategoriju ");
        menuItemAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddCategoryActionPerformed(evt);
            }
        });
        menuMeals.add(menuItemAddCategory);

        jMenuBar1.add(menuMeals);

        menuMenu.setText(" Jelovnik");

        menuItemMenuGetAll.setText("Prikaz jelovnika");
        menuItemMenuGetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMenuGetAllActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemMenuGetAll);

        menuItemCreateNewMenu.setText("Kreiraj novi jelovnik");
        menuItemCreateNewMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateNewMenuActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemCreateNewMenu);

        menuItemUpdateMenu.setText("Izmeni jelovnik");
        menuItemUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUpdateMenuActionPerformed(evt);
            }
        });
        menuMenu.add(menuItemUpdateMenu);

        jMenuBar1.add(menuMenu);

        menuTables.setText("Stolovi");

        menuItemTablesSerach.setText("Pregled svih stolova");
        menuItemTablesSerach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTablesSerachActionPerformed(evt);
            }
        });
        menuTables.add(menuItemTablesSerach);

        jMenuBar1.add(menuTables);

        menuEmployee.setText(" Zaposleni");

        menuItemEmployeeSearch.setText("Pregled svih zaposlenih");
        menuItemEmployeeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmployeeSearchActionPerformed(evt);
            }
        });
        menuEmployee.add(menuItemEmployeeSearch);

        menuItemCreateAccount.setText("Kreiraj nalog zaposlenom");
        menuItemCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateAccountActionPerformed(evt);
            }
        });
        menuEmployee.add(menuItemCreateAccount);

        menuItemAddEmployee.setText("Dodaj novog zaposlenog");
        menuItemAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAddEmployeeActionPerformed(evt);
            }
        });
        menuEmployee.add(menuItemAddEmployee);

        menuItemAccountForm.setText("Pregled svih naloga");
        menuItemAccountForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAccountFormActionPerformed(evt);
            }
        });
        menuEmployee.add(menuItemAccountForm);

        jMenuBar1.add(menuEmployee);

        menuOrder.setText("Porudzbina");

        menuItemGetAllOrder.setText("Pregled svih porudzbina");
        menuItemGetAllOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGetAllOrderActionPerformed(evt);
            }
        });
        menuOrder.add(menuItemGetAllOrder);

        menuItemCreateOrder.setText("Kreiraj porudzbinu");
        menuItemCreateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCreateOrderActionPerformed(evt);
            }
        });
        menuOrder.add(menuItemCreateOrder);

        menuItemPayment.setText("Naplati porudzbinu");
        menuItemPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPaymentActionPerformed(evt);
            }
        });
        menuOrder.add(menuItemPayment);

        menuItemChefsOrder.setText("Kuhinja-Pregled porudzbina");
        menuItemChefsOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemChefsOrderActionPerformed(evt);
            }
        });
        menuOrder.add(menuItemChefsOrder);

        jMenuItem2.setText("Bar - Pregled porudzbina");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuOrder.add(jMenuItem2);

        jMenuBar1.add(menuOrder);

        menuReceipt.setText("Racun");

        jMenuItem1.setText("Pregled svih racuna");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuReceipt.add(jMenuItem1);

        jMenuBar1.add(menuReceipt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(210, 210, 210))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemMenuItemGetAllMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMenuItemGetAllMealsActionPerformed
        new MenuItemSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemMenuItemGetAllMealsActionPerformed

    private void menuItemAddMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddMenuItemActionPerformed
        new MenuItemAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemAddMenuItemActionPerformed

    private void menuItemAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddCategoryActionPerformed
        new MenuCategoryAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemAddCategoryActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try {
            LoginFormController.logout();
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        new LogInForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void menuItemMenuGetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMenuGetAllActionPerformed
        new MenuSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemMenuGetAllActionPerformed

    private void menuItemCreateNewMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateNewMenuActionPerformed
        new MenuAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemCreateNewMenuActionPerformed

    private void menuItemTablesSerachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTablesSerachActionPerformed
        new TableSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemTablesSerachActionPerformed

    private void menuItemEmployeeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmployeeSearchActionPerformed
        new EmployeeSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemEmployeeSearchActionPerformed

    private void menuItemCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateOrderActionPerformed
       
        new OrderCreateForm(this, true).setVisible(true);
       
    }//GEN-LAST:event_menuItemCreateOrderActionPerformed

    private void menuItemUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUpdateMenuActionPerformed
        new MenuUpdateDeleteForm(this, true, null).setVisible(true);
    }//GEN-LAST:event_menuItemUpdateMenuActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        new MenuSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentActionPerformed
      new OrderPreparePaymentForm(this, true).setVisible(true);
    }//GEN-LAST:event_btnPaymentActionPerformed

    private void btnCreateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateOrderActionPerformed
        new OrderCreateForm(this, true).setVisible(true);
    }//GEN-LAST:event_btnCreateOrderActionPerformed

    private void menuItemPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPaymentActionPerformed
        new OrderPreparePaymentForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemPaymentActionPerformed

    private void menuItemGetAllOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGetAllOrderActionPerformed
        new OrderSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemGetAllOrderActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Request request = new Request(Operation.END);
        try {
            Communication.getInstance().getSender().writeObject(request);
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnOrderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderViewActionPerformed
        new OrderChefsForm(this, false).setVisible(true);
    }//GEN-LAST:event_btnOrderViewActionPerformed

    private void menuItemCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCreateAccountActionPerformed
        new EmployeeCreateAccountForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemCreateAccountActionPerformed

    private void menuItemChefsOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemChefsOrderActionPerformed
        new OrderChefsForm(this, false).setVisible(true);
    }//GEN-LAST:event_menuItemChefsOrderActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new ReceiptSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new OrderBartenderForm(this, false).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new OrderBartenderForm(this, false).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void menuItemAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAddEmployeeActionPerformed
        new EmployeeAddForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemAddEmployeeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new TableSearchForm(this, true).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void menuItemAccountFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAccountFormActionPerformed
        new EmployeeAccountUpdateDeleteForm(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemAccountFormActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateOrder;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOrderView;
    private javax.swing.JButton btnPayment;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JMenu menuEmployee;
    private javax.swing.JMenuItem menuItemAccountForm;
    private javax.swing.JMenuItem menuItemAddCategory;
    private javax.swing.JMenuItem menuItemAddEmployee;
    private javax.swing.JMenuItem menuItemAddMenuItem;
    private javax.swing.JMenuItem menuItemChefsOrder;
    private javax.swing.JMenuItem menuItemCreateAccount;
    private javax.swing.JMenuItem menuItemCreateNewMenu;
    private javax.swing.JMenuItem menuItemCreateOrder;
    private javax.swing.JMenuItem menuItemEmployeeSearch;
    private javax.swing.JMenuItem menuItemGetAllOrder;
    private javax.swing.JMenuItem menuItemMenuGetAll;
    private javax.swing.JMenuItem menuItemMenuItemGetAllMeals;
    private javax.swing.JMenuItem menuItemPayment;
    private javax.swing.JMenuItem menuItemTablesSerach;
    private javax.swing.JMenuItem menuItemUpdateMenu;
    private javax.swing.JMenu menuMeals;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenu menuOrder;
    private javax.swing.JMenu menuReceipt;
    private javax.swing.JMenu menuTables;
    // End of variables declaration//GEN-END:variables

    private void prepareForm() {
        
        User user = ApplicationSession.getInstance().getLoginUser();
       
       
        this.setTitle("Prijavljeni ste kao: " + user.getEmployee().getFirstname()+" " + user.getEmployee().getLastname());
        // administrator = 1, sef kuhinje = 2, konobar = 3
       if (user.intRole()==2){
            
            menuEmployee.setEnabled(false);
            menuItemCreateOrder.setEnabled(false);
            menuItemGetAllOrder.setEnabled(false);
            menuItemPayment.setEnabled(false);
            btnCreateOrder.setEnabled(false);
            btnPayment.setEnabled(false);
            
        }
       if(user.intRole()==3){
           menuEmployee.setEnabled(false);
           menuMeals.setEnabled(false);
           menuItemGetAllOrder.setEnabled(false);
//           menuMenu.setEnabled(true);
//           
//           menuItemCreateNewMenu.setEnabled(false);
//           menuMeals.setEnabled(false);
       }
    }


}
